// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf_DF8oV5D-v-a0MqNC3oMdrAjYGxE7K4',
    appId: '1:358503040294:андроид:f9b545aa9108b7cb746de7',
    messagingSenderId: '1022569736671',
    projectId: 'fb-login-2212',
    authDomain: 'fb-login-2212.firebaseapp.com',
    storageBucket: 'fb-login-2212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQBpQMRmwkm2HaQVCbH0jdUofNQ5il90',
    appId: '1:358503040294:андроид:f9b545aa9108b7cb746de7',
    messagingSenderId: '1022569736671',
    projectId: 'fb-login-2212',
    storageBucket: 'fb-login-2212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBuyKa6980p4OkbpObCpwgcI8VgsVviw',
    appId: '1:358503040294:андроид:f9b545aa9108b7cb746de7',
    messagingSenderId: '1022569736671',
    projectId: 'fb-login-2212',
    storageBucket: 'fb-login-2212.appspot.com',
    iosClientId: '1022569736671-8s0h28a54ip084m52c214hcntil8rq1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBuyKa6980p4OkbpObCpwgcI8VgsVviw',
    appId: '1:358503040294:андроид:f9b545aa9108b7cb746de7',
    messagingSenderId: '1022569736671',
    projectId: 'fb-login-2212',
    storageBucket: 'fb-login-2212.appspot.com',
    iosClientId: '1022569736671-8s0h28a54ip084m52c214hcntil8rq1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}